name: Print Hello World

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Hello World
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Hello, World!!"
          gh --version
          gh project item-list --owner RhoderickGalero 6 --format json
