name: Add PR to project

on: [push]

jobs:
  move_to_in_progress:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get project data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_NUMBER: 6
        run: |
          echo "Hello, World!!"
          gh --version
