name: Print In Progress World

on: [push]

jobs:
  In_Progress_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Hello World
        run: |
             query='
             {
               "query": "
               {
               organization(login: "") 
                 { projectsV2(first: 100) {
                   edges { 
                     node {
                       id 
                       } 
                      }
                    }
                  }
                }
              }"
              $response = $(gh api graphql -H "X-Github-Next-Global-ID: 1" -F query=$query | ConvertFrom-Json)
              echo $reponse
