name: Add PR to project

on: [push]

jobs:
  move_to_in_progress:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get project data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_NUMBER: 6
        run: |
          gh api graphql -f query='
            query {
              repository(owner: "owner_name", name: "repo_name") {
                project(number: $PROJECT_NUMBER) {
                  id
                  fields(first: 20) {
                    nodes {
                      ... on ProjectField {
                        id
                        name
                      }
                      ... on ProjectSingleSelectField {
                        id
                        name
                        options {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            }' > project_data.json 
