name: Add PR to project

on: [push]

jobs:
  move_to_in_progress:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get project data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_NUMBER: 6
        run: |
          query='
          {
            "query": "
            {
              repository(owner: "RhoderickGalero", name: "Practice") {
                projects(first: 10) {
                  nodes {
                  id
                  name
                  columns(first: 10) {
                    nodes {
                      id
                      name
                      cards(first: 10) {
                        nodes {
                          id
                          note
                      }
                    }
                  }
                }
              }
            }
          }
          }"
          }' > github/workflows/project_data.json
