name: Move Issues to In Progress Makkan

permissions: write-all

on:
  issues:
    types:
      - assigned
      
  workflow_call:

env:
  repo: "Practice"

jobs:
  move_to_in_progress:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.repository.owner.login}}/Practice
          ref: main
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ISSUE_NR: ${{ github.event.issue.number }}
          path: ${{ env.repo }}

      - name: Do something  
        run: |
          python ${{ env.repo }}/move_to_in_progress_makkan.py
